# Default values for aj-blogs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# 
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/

image:
  repository: bozosapien/hugo-site
  tag: v1.0.20
ingress:
  enabled: true
  host: blogs.aj-labs.ca
  path: /
service:
  port: 80
  targetPort: 80
  type: ClusterIP
