apiVersion: apps/v1
kind: Deployment
metadata:
  name: aj-blogs
  # namespace: aj-hugo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aj-blogs
  template:
    metadata:
      labels:
        app: aj-blogs
    spec:
      containers:
        - name: aj-blogs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
